### PR TITLE
fix: signout properly

### LINKED ISSUE #1: It is necessary to remove cookies when restarting the ui
Is it possible to make it more resilient? It is going to be a problem if the user has to remove cookies to make it run.

image

image

I usually open incognito to make it run:
image
image

### PR DESCRIPTION
**Pull request by HazimAr**
I am open to another way of doing this. We are essentially turning this JWT strategy into a session strategy as we are checking keycloak if the token is valid.

closes #1

### CODE REVIEW

File: ui/src/app/admin/layout.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ export default async function AdminLayout({
   children: React.ReactNode;
 }) {
   const session = await auth();
-  if (!session) return redirect("/api/auth/signout");
+  if (!session) return redirect("/api/signout");
```
Comment (mijailr) [inline ui/src/app/admin/layout.tsx:10]: This should be handled in the middleware instead

Comment (HazimAr) [reply ui/src/app/admin/layout.tsx:10]: I agree

Comment (HazimAr) [reply ui/src/app/admin/layout.tsx:10]: https://github.com/littlehorse-enterprises/lh-user-tasks/pull/18

I'm waiting for this to be merged as it has a custom `middleware.ts` file and we can update this PR to check if the token is valid

**Review by sauljabin — APPROVED** [review]
